### ISSUE TITLE
I realise that in the demo program. The url contain "https://newyork.craigslist.org"twice,is this intentional? or it is actually a wrong url

### ISSUE THREAD

**Issue by Dominic852** [khwang0/2018F-COMP3111#55] opened 2018-11-10 09:18 UTC

**Comment by billy1624** [comment] 2018-11-10 11:05
There is a similar issue regarding the question #32 :)

**Comment by billy1624** [comment] 2018-11-10 11:06
Duplicate of #32

**Closed** 2018-11-12 03:42 UTC
